lib/huberisation_blog_web/router.ex
defmodule HuberisationBlogWeb.Router do
  use HuberisationBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HuberisationBlogWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/register", UserController, :new

    resources "/articles", ArticleController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", HuberisationBlogWeb do
  #   pipe_through :api
  # end
end

lib/huberisation_blog_web/controllers/user_controller.ex
defmodule HuberisationBlogWeb.UserController do
  use HuberisationBlogWeb, :controller

  alias HuberisationBlog.Auth
  alias HuberisationBlog.Auth.User

  def index(conn, _params) do
    users = Auth.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Auth.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Auth.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    changeset = Auth.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Auth.get_user!(id)

    case Auth.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Auth.get_user!(id)
    {:ok, _user} = Auth.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/huberisation_blog_web/views/user_view.ex
defmodule HuberisationBlogWeb.UserView do
  use HuberisationBlogWeb, :view
end

lib/huberisation_blog_web/templates/user/edit.html.eex
<h1>Edit Users</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/huberisation_blog_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Une erreur s'est produite.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :full_name, "Nom et prénom", class: "form-label" %>
    <%= text_input f, :full_name, class: "form-input" %>
    <%= error_tag f, :full_name %>
  </div>

  <div class="form-group">
    <%= label f, :username, "Nom d'utilisateur", class: "form-label" %>
    <%= text_input f, :username, class: "form-input" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "form-label" %>
    <%= text_input f, :email, class: "form-input" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Mot de passe", class: "form-label" %>
    <%= password_input f, :password, class: "form-input" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, "Confirmez le mot de passe", class: "form-label" %>
    <%= password_input f, :password_confirmation, class: "form-input" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group d-none">
    <%= label f, :bio, class: "form-label" %>
    <%= textarea f, :bio, class: "form-input" %>
    <%= error_tag f, :bio %>
  </div>

  <div class="form-group  d-none">
    <%= label f, :is_admin, class: "form-checkbox" %>
    <%= checkbox f, :is_admin %>
    <%= error_tag f, :is_admin %>
  </div>

  <div>
    <%= submit "Save", class: "btn btn-primary form-input" %>
  </div>
<% end %>

lib/huberisation_blog_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.full_name %></td>*

      <td>
        <span><%= link "Show", to: Routes.user_path(@conn, :show, user) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user) %></span>
        <span><%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/huberisation_blog_web/templates/user/new.html.eex
<div class="card login-card mt-2 p-centered">
    <div class="card-header">
        <h2>Nouveau compte</h2>
    </div>

    <div class="card-body">
        <%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>
    </div>
</div>

<div class="card login-card mt-2 p-centered">
    <div class="card-body">
        <%= link "Connexion", to: Routes.session_path(@conn, :new) %>
    </div>
</div>

lib/huberisation_blog_web/templates/user/show.html.eex
<h1>Show User</h1>

<ul>

  <li>
    <strong>Name</strong>
    <%= @user.full_name %>
  </li>

  <li>
    <strong>Bio</strong>
    <%= @user.bio %>
  </li>


</ul>

<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>