lib/huberisation_blog_web/router.ex
defmodule HuberisationBlogWeb.Router do
  use HuberisationBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HuberisationBlogWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/register", UserController, :new

    resources "/articles", ArticleController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", HuberisationBlogWeb do
  #   pipe_through :api
  # end
end

lib/huberisation_blog_web/controllers/session_controller.ex
defmodule HuberisationBlogWeb.SessionController do
  use HuberisationBlogWeb, :controller

  alias HuberisationBlog.Auth
  alias HuberisationBlog.Auth.User

  def new(conn, _params) do
    changeset = Auth.change_user(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    Auth.get_user_by_username(user_params["username"])
    |> sign_in(user_params["password"], conn)
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Signed out successfully!")
    |> redirect(to: Routes.page_path(conn, :index))
  end

  defp sign_in(user, password, conn) when is_nil(user) do
    conn
    |> put_flash(:error, "Invalid username/password combination!")
    |> redirect(to: Routes.session_path(conn, :new))
  end

  defp sign_in(user, password, conn) do
    if Bcrypt.verify_pass(password, user.password_hash) do
      conn
      |> put_session(:current_user, %{id: user.id, username: user.username})
      |> put_flash(:info, "Logged in!")
      |> redirect(to: Routes.page_path(conn, :index))
    else
      conn
      |> put_flash(:error, "Invalid username/password combination!")
      |> redirect(to: Routes.session_path(conn, :new))
    end
  end

end

lib/huberisation_blog_web/views/session_view.ex
defmodule HuberisationBlogWeb.SessionView do
  use HuberisationBlogWeb, :view
end

lib/huberisation_blog_web/templates/session/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if f.errors != [] do %>
<div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below:</p>
    <ul>
        <%= for {attr, message} <- f.errors do %>
        <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
    <%= label f, :username, class: "form-label" %>
    <%= text_input f, :username, class: "form-input" %>
</div>

<div class="form-group">
    <%= label f, :password, class: "form-label" %>
    <%= password_input f, :password, class: "form-input" %>
</div>

<div class="form-group">
    <%= submit "Connexion", class: "btn btn-primary form-input" %>
</div>
<% end %>

lib/huberisation_blog_web/templates/session/new.html.eex
<div class="card login-card mt-2 p-centered">
    <div class="card-header">
        <h2>Connexion</h2>
    </div>

    <div class="card-body">
        <%= render "form.html", Map.put(assigns, :action, Routes.session_path(@conn, :create)) %>
    </div>
</div>

<div class="card login-card mt-2 p-centered">
    <div class="card-body">
        <%= link "Créer un compte", to: Routes.user_path(@conn, :new) %>
    </div>
</div>