lib/huberisation_blog_web/router.ex
defmodule HuberisationBlogWeb.Router do
  use HuberisationBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HuberisationBlogWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    get "/register", UserController, :new

    resources "/articles", ArticleController
    resources "/users", UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", HuberisationBlogWeb do
  #   pipe_through :api
  # end
end

lib/huberisation_blog_web/templates/page/index.html.eex
<div id="home">
<%= if length(@articles) > 0 do %>
<section id="headline">
    <% top_article = hd(@articles) %>

    <img src="<%= top_article.vignette %>" alt="" class="img-fit-cover">
    <div id="headline-card" class="card">
        <div class="card-header">
            <a href="<%= Routes.article_path(@conn, :show, top_article) %>">
                <h4><%= top_article.title %></h4>
            </a>
        </div>
        <div class="card-body">
            <%= top_article.epigraph %>
        </div>
    </div>
</section>


<section id="last-articles" class="container">
    <% latest_articles = tl(@articles) %>
    <%= if length(latest_articles) > 0 do %>
    <h3>Derniers articles</h3>
    <div class="flex">
        <%= for article <- latest_articles do %>
        <div class="card article-thumbnail">
            <div class="card-image">
                <img src="<%= article.vignette %>" alt="" class="img-responsive">
            </div>
            <div class="card-body">
                <a href="<%= Routes.article_path(@conn, :show, top_article) %>">
                    <h5><%= article.title %></h5>
                </a>
                <%= article.epigraph %>
            </div>
        </div>
        <% end %>
    </div>
    <% end %>

</section>

<% else %>

    <div class="empty">
        <div class="empty-title h3">
            Aucun article n'a été publié pour le moment
        </div>
        <div class="empty-action">
            <%= link "Publier un article", to: Routes.article_path(@conn, :new), class: "btn btn-primary" %>
        </div>
    </div>

<% end %>

</div>